---
- name: Setup Docker and Docker Compose
  hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Update apt packages after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      loop: 
        - docker.io
        - docker-compose

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
